class constant:
    NUM_PATCHES = 15
    DIAGONAL_TO_CENTER = 90
    DIAGONAL_TO_CENTER_ARC = DIAGONAL_TO_CENTER*2
    DISTANCE_MIN_BETW_GABORS = 30
    GABOR_SIZE = 30
    NUMBER_TRIALS = 10
    NUMBER_BLOCKS = 2
