class constant:
    NUM_PATCHES = 15
    DIAGONAL_TO_CENTER = 70
    DIAGONAL_TO_CENTER_ARC = DIAGONAL_TO_CENTER+70
    DISTANCE_MIN_BETW_GABORS = 20
    GABOR_SIZE = 20
    NUMBER_TRIALS = 10
    NUMBER_BLOCKS = 2
